### DISCUSSION TITLE
Pgen in the specification

### DISCUSSION THREAD

**Discussion by jwhite242** [llnl/maestrowf#386] [Design]
Just starting a discussion on some potential design changes in the spec regarding the parameter generators.  The problem this aims to solve is the lack of embedded documentation on a spec that's designed to be run with pgen functions.  So, maybe we can add a new block to the spec to function as a default invocation of the pgen, which would also document it, while also still allowing the cli invocations to override it.  So, something like this:

``` yaml
...
parameter.generator:
    description: simple parameter generator example
    path: mypgen.py
    pargs:
        - arg1: some_value
        - arg2: another_value
```

One thought here is what about spec's that could have multiple pgen's instead of having one giant one that can do many things? (i.e. different parameter sampling strategies).  Perhaps enable making the generator entries a list, with another key under parameter generator specifying the default_pgen:

``` yaml
parameter.generator:
    default_pgen: mypgen    # must be one of the names below, which schema can check for
    generators:
      - name: mypgen
        description: simple parameter generator example
        path: mypgen.py
        pargs:
            - arg1: some_value
            - arg2: another_value

      - name: myotherpgen
        description: another simple parameter generator example
        path: myotherpgen.py
        pargs:
            - arg1: some_value
            - arg2: another_value
```

Additionally, we could treat these similarly to the dependency block, with a check on them being at the specified path and block study launch if not.  Or maybe some more flexiblity like keying on whether default_pgen is empty or not and if it is, use the global.parameters instead or something?

**Comment by jwhite242** [comment]
One more potential ease of use addition to this would be some sort of addition to maestro's cli to use an existing pgen to populate this block in a spec.  something like:

```console
$ maestro attach mypgen.py spec.yaml -o new_spec.yaml
```
And perhaps a component of making this work would be requiring (or encouraging if introspection might work too) numpydoc/googledoc docstrings on the pgen function from which the description and pargs could be parsed from the pgen itself, ensuring the spec is in-sync with the pgen function.

So, taking one of the parg examples from the docs and updating it:

```python
from maestrowf.datastructures.core import ParameterGenerator
import itertools as iter

def get_custom_generator(env, **kwargs):
    '''
    Simple filtering parameter generator example

    Parameters
    ------------
    env: dict
        Environment block from the yaml specification

    SIZE_MIN: int, default=10
        Set minimum size of generated parameter set

    SIZE_STEP: int, default=10
        Increment between sizes in generated parameter set

    NUM_SIZES: int, default=3
        Number of parameter sets to generate for sampling the SIZE parameter
    
    Returns
    --------
    ParameterGenerator containing selected parameter sets
    '''
    p_gen = ParameterGenerator()

    # Unpack any pargs passed in
    size_min = int(kwargs.get('SIZE_MIN', '10'))
    size_step = int(kwargs.get('SIZE_STEP', '10'))
    num_sizes = int(kwargs.get('NUM_SIZES', '3'))

    sizes = range(size_min, size_min+num_sizes*size_step, size_step)
    iterations = (10, 20, 30)

    size_values = []
    iteration_values = []
    trial_values = []

    for trial, param_combo in enumerate(iter.product(sizes, iterations)):
        size_values.append(param_combo[0])
        iteration_values.append(param_combo[1])
        trial_values.append(trial)

    params = {
        "TRIAL": {
            "values": trial_values,
            "label": "TRIAL.%%"
        },
        "SIZE": {
            "values": size_values,
            "label": "SIZE.%%"
        },
        "ITER": {
            "values": iteration_values,
            "label": "ITER.%%"
        },
    }

    for key, value in params.items():
        p_gen.add_parameter(key, value["values"], value["label"])

    return p_gen

```

That could then be used to auto generate the following section in the yaml spec with the initial attach invocation:

```yaml
parameter.generator:
    default_pgen: mypgen    # must be one of the names below, which schema can check for
    generators:
      - name: mypgen
        description: Simple filtering parameter generator example
        path: mypgen.py
        pargs:
            - SIZE_MIN: 10
            - SIZE_STEP: 10
            - NUM_SIZES: 3
```

Still leaves the question of whether we could automate documenting constants in some manner this way (the iterations parameter in the above pgen)...  Though maybe that would be best in the docstring of the pgen?
