### ISSUE TITLE
slurm job names

### ISSUE THREAD

**Issue by doutriaux1** [LLNL/maestrowf#213]
When scheduling a job with slurm e.g:

```yaml
description:
  name: ibm_postprocess
  description: Does all post processing after we run shocktube

batch:
  type:  slurm
  queue: pbatch
  host:  surface
  bank:  cbronze

study:
  - name: hdf5
    description: Generates hdf5 files from MashExtract
    run:
      cmd: |
         binary_2_hdf5.py -r $(RUN) -m "{'node': None}" --root=$(IBM_PATH)/base
      depends: []
      nodes: 1
      procs: 1
      walltime: "24:00:00"
      depends: []
```

In the directory the `hdf5` step I get:

```
-rwx------ 1 cdoutrix cdoutrix 339 Jan  6 13:09 hdf5_RUN.molar.0.0_shock.1.1_taper.0.9_skew.0.9.slurm.sh
-rw------- 1 cdoutrix cdoutrix   0 Jan  6 13:09 slurm-374670.out
```

It would be nice to get the job name output to match the `.sh` file.

I believe the slurm option is:

```
#SBATCH --job-name="[name here]"
```
