### ISSUE TITLE
Path dependency value not being stored

### ISSUE THREAD

**Issue by kozuch1** [LLNL/maestrowf#230]
It appears that the path dependency feature is not working properly for me. My study.yaml file contains:

```yaml
env:
    variables:
        OUTPUT_PATH: /my/output/path

    dependencies:
        path:
          - name: my-dependency-name
            path: /my/dependency/path
```

However, in my run commands, when I try to use $(my-dependency-name), the expression does not get replaced with the value. I ran in debug mode, and there is no output under "Processing dependencies" which seems to suggest that the dependency was never stored. Any ideas what I did wrong?

**Comment by FrankD412** [comment]
Hi @kozuch1 -- thanks for the issue. It appears that in your specification you're put `path` and not `paths`. The key is actually plural, it's a slight nuance but that's what the check in code currently looks for. Your new block should be:

```
env:
    variables:
        OUTPUT_PATH: /my/output/path

    dependencies:
        paths:
          - name: my-dependency-name
            path: /my/dependency/path
```

Please let me know if that helps.
