### ISSUE TITLE
would be nice to be able to override global env from user env

### ISSUE THREAD

**Issue by doutriaux1** [LLNL/maestrowf#237]
I would be nice to be able to let the user "alter" the global.env section using the user's env 
example:

maestro file:
```yaml
description:
  name: test_env_var
  description: Test if env variable overwrite what's in yaml file

env:
  labels:
      SOME_VAR: COMING_FROM_YAML

study:
      - name: echo_var
        description: print the variable value
        run:
          cmd: |
            echo $(SOME_VAR)
          depends: []
```

now running the following :

```
maestro run simple.yaml
```
or 
```
export SOME_VAR="COMING FROM ENV"
maestro run simple.yaml
```
or
```
env SOME_VAR="CMDLINE" maestro run simple.yaml
```

leads to:
```
more test_env_var_*/echo_var/echo_var.out
::::::::::::::
test_env_var_20200319-152218/echo_var/echo_var.out
::::::::::::::
COMING_FROM_YAML
::::::::::::::
test_env_var_20200319-152319/echo_var/echo_var.out
::::::::::::::
COMING_FROM_YAML
::::::::::::::
test_env_var_20200319-152436/echo_var/echo_var.out
::::::::::::::
COMING_FROM_YAML
```

It would be nice to retun:
```
more test_env_var_*/echo_var/echo_var.out
::::::::::::::
test_env_var_20200319-152218/echo_var/echo_var.out
::::::::::::::
COMING_FROM_YAML
::::::::::::::
test_env_var_20200319-152319/echo_var/echo_var.out
::::::::::::::
COMING FROM ENV
::::::::::::::
test_env_var_20200319-152436/echo_var/echo_var.out
::::::::::::::
CMD_LINE
```
