### ISSUE TITLE
Double depth env variables are not expended

### ISSUE THREAD

**Issue by doutriaux1** [LLNL/maestrowf#253]
In the global env section if i define a variable and then another one depending on this one. Everything is fine, But if i define a thrid env varialbe depending on the second one it does not get expanded fully in the bash script

example yaml file:
```yaml
description:
  name: double_env_var
  description: env var with double def seems to be untouched in script

env:
  labels:
      TOP_DIR: $HOME/maestro
      SOME_PATH: $(TOP_DIR)/somedir
      CONFIG_FILE: $(SOME_PATH)/config.ini

global.parameters:
    PARAM:
        values: [1, 2]
        label: param_%%

study:
    - name: show_issue
      description: should die in bash
      run:
          cmd: |
              echo "$(PARAM) config file is in $(SOME_PATH) at: $(CONFIG_FILE)"
          depends: []
```

I get a runtime error:
```
/g/g19/cdoutrix/maestro/double_env_var_20200423-072614/show_issue/param_1/show_issue_param_1.sh: line 3: SOME_PATH: command not found
```

Indeed var is not expendaded properly in .sh file:
```bash
#!/bin/bash

echo "1 config file is in $HOME/maestro/somedir at: $(SOME_PATH)/config.ini"
```

Notice that `SOME_PATH` was expanded in script but `CONFIG_FILE` was expanded to `SOME_PATH` which is now unknown from the bash

It's not a big issue and i caneasily work around this, but you might want to expand fully all global env variable before substituting them in bash scripts.

**Comment by FrankD412** [comment]
@doutriaux1 -- The `labels` section of the specification was never meant to support the recursive style of substitution, much like the `variables` section. In its current implementation, there is no guarantee that variables/labels are added in any given order. I suggest something like the following:

```
env:
  variables:
      TOP_DIR: $HOME/maestro/somedir
  labels:
      CONFIG_FILE: $(TOP_DIR)/config.ini
```

Alternatively, if you want to be able to change `somedir` then the following would achieve what you're after:

```
env:
  variables:
      TOP_DIR: $HOME/maestro
      SUB_DIR: somedir
  labels:
      CONFIG_FILE: $(TOP_DIR)/$(SUB_DIR)/config.ini
```

Variables are never resolved, nor are labels technically. The fact that some work just fine while others don't is an artifact of implementation, and not meant to be a feature nor is it a bug.

I've considered allowing in line variable substitutions, but that would mean that users could make specs that do not resolve (albeit, I can time out). I opted to implement it this way because not allowing nested substitutions is much clearer and straight-forward and favors clearer documentation.

Please let me know if this answers your question.

Thanks!
Frank
