### ISSUE TITLE
maestro not catching msub errors

### ISSUE THREAD

**Issue by crkrenn** [LLNL/maestrowf#261]
This is a general problem, but I have a specific example: 

If I use `walltime: "0.9"` in a `study.yaml`, maestro generates a batch script with `#SBATCH -t 0.9`.  Running `msub` with this script gives an error `sbatch: error: Invalid --time specification`, but running `maestro run -y study.yaml` results in `Study launched successfully.`

Using `walltime: "1"` in `study.yaml` results in successful job submission. 

And, when I `grep  -e sbatch -R *` in the study directory the `sbatch: error: Invalid --time specification` does not show up anywhere. 

This is a general problem, because there are many other sbatch errors that can occur, and (during emergency response operations), finding these quickly is important. 

```
description:
    name: codepy-study
    description: |
        codepy-study         

batch:
    type: slurm
    host: rztopaz
    bank: wbronze
    queue: pbatch
    gres: ignore

env:
    variables:
        OUTPUT_PATH: /p/lustre1/crkrenn/studies
        
        MHD_INPUT: mhd_liner.deck

    dependencies:
        paths:
            - name: ARES
              path: /usr/apps/ARES/exec/ares.prod

            - name: MHD
              path: /g/g21/crkrenn/ares-models/ares-models/mhd_liner

            - name: MHD_INPUT_PATH
              path: /g/g21/crkrenn/ares-models/ares-models/mhd_liner/model.yaml

study:
    - name: run-mhd
      description: |
          TBD      
      run:
          cmd: |

              cp -L -r $(MHD)/* ./

              $(LAUNCHER) $(ARES) $(MHD_INPUT) -r -def rLiner=$(rLiner) -def tLiner=$(tLiner)

          nodes: 2
          procs: 72
          walltime: "0.9"
          depends: []


global.parameters:

    rLiner:
        values: [0.3168,0.33,0.30]
        label: rLiner.%%

    tLiner:
        values: [0.0292,0.02,0.04]
        label: tLiner.%%
```
