### ISSUE TITLE
Add maestro play feature

### ISSUE THREAD

**Issue by jsemler** [LLNL/maestrowf#286]
This feature would introduce a new config file for specifying a Maestro study to run along with available run options. This would make it easier to run more complex Maestro studies more easily while still decoupling run configurations from the study spec.

The following Maestro study could then be written to a new config file:

```
-  study: study1.yaml
   pgen: pgen1.py
   throttle: 20
```

The new file could also allow multiple Maestro study specs to be configured.

```
-  study: study1.yaml
   pgen: pgen1.py
   throttle: 20

-  study: study2.yaml
   pgen: pgen2.py
   throttle: 10
```

The studies would be launched via a new option:

```
maestro play <filepath>
```

Thoughts, feedback, and suggestions are welcome.

**Comment by jsemler** [comment]
Tagging @crkrenn and @FrankD412

**Comment by jwhite242** [comment]
pgen args?  maybe something like this:

```
- study: study1.yaml
  pgen: pgen1.py
  pgen_args:
    - arg1: val1
    - arg2: val2
```

**Comment by jsemler** [comment]
@jwhite242 -- Yeah, that would be a reasonable format.

**Comment by FrankD412** [comment]
I've been thinking about this over the last few days. I wonder if it might be worth doing something similar to a study specification and having a description and some high level settings.

```
name: <name>
description: Ensemble of studies to test x, y, z
OUTPUT_PATH: <central path to store studies>

studies:
- spec: <path>.yaml
  pgen: pgen1.py
  pgen_args:
    - arg1: val1
    - arg2: val2
```
