### ISSUE TITLE
slurm script adapter does not handle per-step procs correctly

### ISSUE THREAD

**Issue by tadesautels** [LLNL/maestrowf#297]
If I specify a study script like so:

```
batch:
  type: slurm
  queue: pbatch
  bank: abank
  host: amachine

study:
  - name: local-step
    description: locally-executed
    run: 
      cmd: |
          echo "do stuff"
      depends: []
  - name: scheduled-step
     description: scheduled
     run: 
        cmd: |
          echo "Do scheduled stuff"
        procs: 4
        walltime: 24:00:00
        depends: [local-step]
```

The SLURM scheduled step is scheduled, but the job does not have a `# SBATCH --ntasks=4`  line specifying the number of tasks.

However, if i add `procs: 4` to the batch line, this step is scheduled (the previous local one is correctly NOT scheduled) and the  `# SBATCH -n 4` appears correctly.
