### ISSUE TITLE
Add qos option to slurm adaptor

### ISSUE THREAD

**Issue by daub1** [LLNL/maestrowf#336]
Allow specifying the `qos` parameter for slurm via the batch block.

```
batch:
    type: slurm
    ...
    qos: standby

```

Leading to the additional header line:
```
#SBATCH --qos=standby
```
