### ISSUE TITLE
missing SBATCH options for cpus-per-task

### ISSUE THREAD

**Issue by das046** [LLNL/maestrowf#340]
Hi,

I was trying to use maestrowf to submit jobs. I could set the number of CPUs (cores per task) of the job in the YAML file, something like below. 
```
 name: model_predictor
      description: Model Predictor
      run:
          cmd: |
              args=(
                -w model_predictor_QED
                -w model_predictor_SAS
                -w model_predictor_AurkA
                -w model_predictor_AurkB
                -w model_predictor_Clearance
                -w model_predictor_Solubility
                -w model_predictor_hERG
                -w model_predictor_BSEP
                -c $(CONFIG_FILE)
              )
              $(LAUNCHER) $(SPL_CMD) ${args[@]}
          depends: [generate_config]
          walltime: $(WALL_TIME)
          nodes: 1
          procs: 1
          cores per task: 2
```
It would generate the following slurm script to be submitted. 
```#!/bin/bash
#SBATCH --nodes=1
#SBATCH --partition=gpu
#SBATCH --time=720
#SBATCH --job-name="model_predictor"
#SBATCH --output="model_predictor.out"
#SBATCH --error="model_predictor.err"
#SBATCH --comment "Model Predictor"

args=(
  -w model_predictor_QED
  -w model_predictor_SAS
  -w model_predictor_AurkA
  -w model_predictor_AurkB
  -w model_predictor_Clearance
  -w model_predictor_Solubility
  -w model_predictor_hERG
  -w model_predictor_BSEP
  -c /scratch/cluster_scratch/shid6/aurk_output/glo_spl_config.yaml
)
srun -n 1 -N 1 -c 2 atomsci_glo_spl ${args[@]}
```
The `cores per task` option corresponded to the `-c 2` in the `srun` line. But there is no option `#SBATCH --cpus-per-task=2` above, that would cause errors in the SLURM of our cluster. Could you add this modify the code and add this option? I believe it won't break other parts. 

Thank you,

Da Shi
Frederick National Lab

**Comment by FrankD412** [comment]
Thanks for posting @das046 -- I'll take a look at this soon. This issue has some implications on the specification which might break backward compatibility. I just tested this on my end, and I was able to inject something as follows:

```
    - name: run-lulesh
      description: Run LULESH.
      run:
          cmd: |
            #SBATCH --cpus-per-task=2

            $(LAUNCHER) -c 2 $(LULESH)/build/lulesh2.0 -s $(SIZE) -i $(ITERATIONS) -p > $(outfile)
          depends: [make-lulesh]
          nodes: 2
          procs: 27
          exclusive   : True
          walltime: "00:10:00"
```

A workaround to just get you running would be to hardcode the `#SBATCH --cpus-per-task=<num>` as I did above. That'll get you moving in the meantime while I figure the actual issue.

Thanks for your issue! :)
