### ISSUE TITLE
Parallelization on a single node level 

### ISSUE THREAD

**Issue by TobiasDuswald** [LLNL/maestrowf#383]
Dear Maestro-developers,

I wanted to use Maestro in a research project that involves the calibration of a stochastic model. The model is rather cheap (~ 15 seconds, single core, does not scale) and I wanted to see if I can speed up the sensitivity analysis with Maestro. I have access to a 72 core machine and my hope was to run 72 models with different parameters in parallel to accelerate the process. I'm sure Maestro does introduce some overhead but I was hoping that the factor 72 outweighs it. I've managed to get everything running and assumed that blocks with no dependences should be executed in parallel but it turned out out that the models are executed sequentially. I reckon that was a little naiv. Anyways, my basic setup is the following at the moment (running locally on my 8 core notebook):

```yaml
batch:
    shell: /bin/zsh

study:
    - name: compile-forward-model
          description: Does not matter here
          ...
      
    - name: run-simulation
          description: Run simulation for given parameter sets
          run:
              cmd: |
                $(compile-forward-model.workspace)/build/my_model <my_param_1> <my_param_2>
              depends: [compile-forward-model]
```

I've checked the repository and the documentation but was not able to find an answer to my question. So I wondered if Maestro supports the kind of parallelism that I'm looking for, and if so, what kind of keywords do I need to include to end up where I want to be? Basically locally with `n_workers = n_processors`.

Thank you very much for your help & kind regards,
Tobias
