### ISSUE TITLE
SLURM: specifying extra arguments for GPU binding

### ISSUE THREAD

**Issue by BenWibking** [LLNL/maestrowf#436]
Is there a recommended way to specify extra SLURM options for GPU bindings?

I tried using the `args:` batch block key (https://maestrowf.readthedocs.io/en/latest/Maestro/scheduling.html), but the options did not get propagated to the *.sh job script.

Following https://github.com/LLNL/maestrowf/issues/340, the workaround I've used so far is to specify these options as part of the run command so that they get copied into the job script:
```
    - name: run-sim
      description: Run the simulation.
      run:
          cmd: |
              #SBATCH --mem=0
              #SBATCH --constraint="scratch"
              #SBATCH --ntasks-per-node=4
              #SBATCH --cpus-per-task=16
              #SBATCH --gpus-per-task=1
              #SBATCH --gpu-bind=none

              srun bash -c "
                  export CUDA_VISIBLE_DEVICES=\$((3-SLURM_LOCALID));
                  $(BINARY_PATH) -i $(generate-infile.workspace)/params.in" > logfile.txt
          depends: [generate-infile]
          nodes: 1
          exclusive: True
          walltime: "00:10:00"
```
