### ISSUE TITLE
Batch additonal args does not work

### ISSUE THREAD

**Issue by EverettGrethel** [LLNL/maestrowf#447]
The Maestro documentation states that custom arguments `args` can be passed to the `batch` block such that the user can specify additional scheduler writing steps that are not default keys in Maestro. The docs state that `args` is passed as a dictionary in the `yaml` file. For example: 
```
batch:
    type: lsf
    host: lassen
    bank: flask
    queue: pdebug
    args:
      alloc_flags: ipisolate
```
which should result in writing a bash script like so:
```
#BSUB -nnodes 1
#BSUB -q pdebug
#BSUB -G flask
#BSUB -W 00:30
#BSUB -alloc_flags ipisolate
```
However, `#BSUB -alloc_flags ipisolate`. My guess is that the code that would be writing this would be located in `maestrowf/interfaces/script/lsfscriptadapter.py`, but as far as I can tell, no code related to `args` is present.
