### ISSUE TITLE
sharing steps across studies

### ISSUE THREAD

**Issue by doutriaux1** [LLNL/maestrowf#452]
It would be great to be able to share some steps across studies, e.g. some pre-processing

example

```yaml
study:
    - name: step1
      description: preproc
      run:
          cmd: |
            echo "Some preprocesisng code here, possibly long
          procs: 1
          nodes: 1
          walltime: "00:01:00"
    - name: step2
      description: some code
      run:
          cmd: |
            echo "Actual work"
            $(LAUNCHER) $(CODE) -in $(MODEL1)

          procs: 1
          nodes: 1
          walltime: "00:01:00"
```

assuming step1 is shared by many maeastro studies it could become something like this:

```yaml
study:
    - name: step1
      path: $(SHARED_MAESTRO_FILES)/preprocessing.yml
      step: standard_preproc
    - name: step2
      description: some code
      run:
          cmd: |
            echo "Actual work"
            $(LAUNCHER) $(CODE) -in $(MODEL1)

          procs: 1
          nodes: 1
          walltime: "00:01:00"
          depends: step1
```

And the preprocessing.yml file could look like this

```yaml
study:
    - name: standard_preproc
      description: standard preprocessing
      run:
          cmd: |
            echo "Some preprocessing code here, possibly long
          procs: 1
          nodes: 1
          walltime: "00:01:00"
    
    - name: advanced_preproc
      description: a more advanced preprocessing step
      run:
          cmd: |
            echo "Some preprocessing code here, possibly long
          procs: 1
          nodes: 1
          walltime: "00:01:00"
    
```

That way we can share and update the preprocessing step across many studies. I do realize this is not great for provenance, but maestro could build a "Final" yml file with the pieces brought over from all the external yml files. 

The concept could also be exported to resources where a resources.yml could exit in a standard place but with diffierent values depending on the machine you're running on.

**Comment by murray55** [comment]
Hey Charles, Thanks for adding this issue! I think a lot of folks could benefit from this. I have several users (myself included) who are interested in breaking out pieces of their workflows into separate specifications, with one primary "driver" spec that links them all together. This would also allow users to own and maintain their specific models while allowing for a simpler handoffs of multi-step workflows.

**Comment by jwhite242** [comment]
This is an interesting feature request.  While I appreciate the idea and the potential value it could bring, I have some concerns about implementing this feature directly within Maestro due to the inherent complexity of the problem.

**Concerns with Template Re-usability in Maestro**

Maestro’s current design is focused on managing workflows with a relatively static structure (i.e. static spec, but not necessarily logic free), and the spec format doesn’t inherently carry enough information to handle dynamic template reuse beyond the most trivial cases. For example, while it’s straightforward to reuse workflows with identical parameters, things become significantly more complex when variations arise, such as adding or removing parameters or handling arguments with specific prefixes (e.g., say `-ivar $(INPUT_PARAM1)`) or flags (e.g., `-r`).

Consider the example you provided with varying numbers of `-ivar` inputs:
```
study:
    ...
    - name: step2
      description: some code
      run:
          cmd: |
            echo "Actual work"
            $(LAUNCHER) $(CODE) -in $(MODEL1) -ivar $(INPUT_PARAM1) -ivar $(INPUT_PARAM2) -r

          procs: 1
          nodes: 1
          walltime: "00:01:00"
```
Maestro would need to understand not only how to add or remove parameters but also how to preserve the correct syntax and placement of these arguments in the command string, potentially multiple lines line with `\` breaks at that. This becomes even more challenging when additional arguments or flags are introduced that are unrelated to parameters such as a simple flag on the end like the `-r`. Without a more robust template mechanism, Maestro simply doesn’t have the context needed to manipulate these variations effectively.

Moreover, the feature request seems to suggest that Maestro should be able to unravel and manipulate specs dynamically, but the current spec format doesn’t include the necessary metadata to support this (those specs are ~rendered templates). At best, it could handle trivial cases like parameter value changes or renaming, but even renaming introduces challenges due to the syntax overlap with bash constructs (e.g., `$( )`) that makes any error checking/validation dicey (`global.parameters` is optional so you don't always have a list of parameters to validate in the source specs).

**Alternative Solutions**

While I don’t think this feature is a good fit for Maestro in its current form, I’d like to suggest an alternative approach that might better suit your needs: templating libraries like Jinja. Jinja templates (or similar tools) are well-suited for this type of problem, as they provide the flexibility to define reusable components with the necessary metadata to handle parameter variations, argument prefixes, and other complexities. Using Jinja to generate Maestro specs would allow you to robustly manage dynamic workflows while leveraging Maestro’s strengths in orchestrating tasks and dependencies.

This approach would give you the ability to create reusable templates tailored to your specific use case, while still outputting valid Maestro specs, and even calling Maestro as part of that to run it all in one go to really streamline things.

**Related Idea: Interactive Spec Editor**

On a related note, I do think there’s an interesting opportunity to explore an interactive spec editor/composer. This could allow users to pick and pull from existing specs, make necessary tweaks, and compose new workflows interactively. While this idea is intriguing, I want to be upfront that implementing such a tool would require significant effort and resources, and it’s not something I can promise in the near term. However, I am rebuilding the study monitoring system using the Textual package, which might provide a foundation for exploring this concept in the future without having to build a more heavyweight gui.  This kind of feature would be a great way to more quickly bootstrap a study from built in examples/spec templates at the very least.  

**Next Steps**

In the meantime, I encourage you to experiment with templating libraries like Jinja for your workflow needs.  Having seen a few users implementations of this, and building a few myself, I think it can enable most/all of what you are looking for right now.  Additionally, if you’d like to discuss the interactive spec editor idea further or share feedback on how you envision it working, I’m open to hearing your thoughts.
