### ISSUE TITLE
Inputs and Source Code Context in the jobs

### ISSUE THREAD

**Issue by faical-yannick-congo** [LLNL/maestrowf#52]
When running the study, since maestrowf is generating scripts and dispatching them with a scheduler, is there a policy to where the data and the code should be.
Do i have to have the code and the data with the study for it to be copied with the spec or make a clone/download of the both before running the code in each step?
I am asking this because in some cases we want to leave at least the data outside of the study and do fullpath/relativepath to it.

**Comment by FrankD412** [comment]
There are ways currently to specify git and path dependencies in the specification.

To pull in a git repository, use the following syntax:
```
env:
    dependencies:
        git:
            - name: GITREPO
               url: <ssh or http url to remote repository>
               path: path/to/where/repo/will/be/checked/out/to
```
Maestro will automatically check out the repository before each study. There are also other keys that can be used -- tag, branch, or hash are entries that can be added to the entries if you'd like to pull out specific commits. Even further, you can use variables in those entries -- so what I do when running a study is to set the path to ```$(OUTPUT_PATH)/subdirectory``` that way a new copy is checked out every time to make the study more reproducible.

Alternatively, if you want to reuse a centralized repository located at a specific path the following works. The only thing Maestro does with path dependencies when it attempts to acquire them is check if they exist. The syntax for that is as follows:
```
env:
    dependencies:
        paths:
            - name: PATH
              path: /path/to/directory
```
You can then refer to the dependencies like any variable (the examples above would be ```$(GITREPO)``` and ```$(PATH)```, respectively). One thing you bring up I hadn't thought of is having a web dependency (URLs that get curled and so on). Does that cover what you were thinking? Are there additional requirements you were thinking of?
