### ISSUE TITLE
Add the ability to specify other types of resources

### ISSUE THREAD

**Issue by FrankD412** [LLNL/maestrowf#76]
This issue address the need to be able to specify resources that are not the standard set of processors and nodes through a scheduler. Those resources include (but are not limited to) GPUs, ASICs, and other forms of scheduler assignable hardware. The items that this issue should address at the very core are as follows:

- Addition of specification notation for requesting resources.
- New logic to existing abstract and concrete scheduler adapters for formatting the request.

A potential format for the YAML study step could be as follows:
```
- name: legacy-token-prepend
      description:
          The legacy format for simply appending all of the step's resources to
          a single command. Procs is the only resource required for this format.
      run:
          cmd: |
            $(LAUNCHER) echo "Test print #1"
          depends: []
      resources:
          nodes: 1
          procs: 1
          gpus: 2
```

The idea would be that the ```resources``` dictionary is kind of a catch-all for resources. Each adapter would be responsible for throwing an exception if specified resources are not capable of being requested with a particular scheduler.
